### ISSUE TITLE
ID and serial number extraction

### ISSUE THREAD

**Issue by jhmigueles** [Unisens/unisensR#7]
Hi, I cannot find the way to get the ID and serial number from data collected with a movisens device. Can you facilitate that in a function? E.g., readUnisensID and/or readUnisensSerialNumber?

**Comment by jottenbacher** [comment]
I would propose:

getMeasurementId() -> ID of the measurement (can be set in SensorManager when starting a measurement)
getTimestampStart() -> start of measurement

And for additional infos from custom attributes:
getCustomAttribute('sensorSerialNumber') -> The SN of the sensor, printed on sensor label
getCustomAttribute('personId') -> optional person ID (can be set in SensorManager when starting a measurement)

**Comment by vincentvanhees** [comment]
> I would propose:

Do you mean that this is how you propose unisensR to be enhanced or are you referring to existing functionality? If it is the latter: Where can we find these functions?

**Comment by vincentvanhees** [comment]
>  get the ID and serial number

It may be better to immediately extract all descriptive information from the file, because other users may need that. At the moment unisensR users are expected to master .xml file handling without having clear insight into how xml-format has changed between Movisense products. 

**What would be helpful is:**
A simple helper function inside unisensR that extracts all the key descriptive information from the recording while accounting for possible variations in the xml formats between Movisense products, and finally putting it in an R data.frame.

**Comment by jottenbacher** [comment]
unisens is a generic data format, not only used for movisens sensors. datasets from other origin will have other attributes.

**Comment by vincentvanhees** [comment]
> unisens is a generic data format

thanks that is clear now.

Where can I find the `getCustomAttribute` function? Is it part of an existing R package?

**Comment by jottenbacher** [comment]
we will add that to unisensR

**Comment by vincentvanhees** [comment]
if Jairo or I can help test this then let us know.

**Comment by jottenbacher** [comment]
uploaded new version, please check if this works for you

**Comment by vincentvanhees** [comment]
I can confirm that this works, thanks.

@jhmigueles if you want to test this too then you could for example do:

`serialnumber = getUnisensCustomAttributes(unisensFolder)[["sensorSerialNumber"]]`
`ID = getUnisensMeasurementId(unisensFolder)`

**Comment by jhmigueles** [comment]
Also checked and worked fine for me. Thanks!

**Comment by vincentvanhees** [comment]
@jottenbacher When will these updates be made available on CRAN? I see the [CRAN version of UnisensR](https://cran.r-project.org/web/packages/unisensR/index.html) has not been updated since 2020, while the above updates were made in 2022. It would be great if CRAN could be kept up to date as well. Let me know if there is anything I can do to help.

**Comment by mpenzel5** [comment]
@vincentvanhees the updates are now available as a new package version [0.3.4 on CRAN](https://cran.r-project.org/web/packages/unisensR/index.html) as well. Best regards
